version: '3.8'
services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: fastapi
    container_name: project_backend
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 127.0.0.1 --reload'
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    depends_on:
      - db
    ports:
    - "8000:8000"
    restart: "on-failure"
  db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_DB=fundacion_vet
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data/db:/var/lib/postgresql/14/main
    restart: "on-failure"
    container_name: db
volumes:
  psql_data:
    driver: local